ui: tape
browsers:
  - name: chrome
    version: 40..latest
  - name: firefox
    version: 31..latest
  - name: ie
    version: 9..latest
  - name: safari
    version: 5..latest
  - name: opera
    version: 11..latest
