ui: tape
capabilities:
  record-video: false
  record-screenshots: false
browsers:
  - name: firefox
    version: [61,62]
    platform: Windows 10
  - name: chrome
    version: [68,69]
    platform: Windows 10
  - name: ie
    version: 11
    platform: Windows 10
  - name: MicrosoftEdge
    platform: Windows 10
    version: latest
  - name: safari
    version: latest