ui: tape
browsers:
  - name: chrome
    version: 26..latest
  - name: firefox
    version: 16..latest
  - name: ie
    version: 8..latest
  - name: safari
    version: 5..latest
  - name: opera
    version: 11..latest
