ui: tape
browsers:
  - name: android
    version: 4.4
    platform: Linux
  - name: android
    version: 5.0
    platform: Linux
  - name: firefox
    version: 36
    platform: Windows 8.1
  - name: firefox
    version: 35
    platform: Windows 8.1
  - name: chrome
    version: 41
    platform: Windows 8.1
  - name: chrome
    version: 40
    platform: Windows 8.1
  - name: ie
    version: 11
    platform: Windows 8.1
  - name: ie
    version: 8
    platform: Windows 7
  - name: ie
    version: 10
    platform: Windows 8
  - name: ie
    version: 9
    platform: Windows 7
  - name: opera
    version: 11
    platform: Windows 7
  - name: opera
    version: 12
    platform: Windows 7
  - name: ipad
    version: 8.1
    platform: OS X 10.9
  - name: ipad
    version: 4
    platform: OS X 10.6
  - name: safari
    version: 8
    platform: OS X 10.10
  - name: safari
    version: 7
    platform: OS X 10.9
  - name: safari
    version: 6
    platform: OS X 10.8
  - name: safari
    version: 5
    platform: OS X 10.6
